#!/usr/bin/env python3
"""Generate display macros from preserved E6 PC2 results; never run a solver.

Run from paper/source: python3 -B scripts/generate_pc2_case_macros.py --check
Default mode writes only build/generated/pc2-case-macros.tex.
--emit-patch emits that new output as an apply_patch-compatible patch.
JSON pointers and distinct state-count denominators are retained in the output.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

from public_evidence import artifact_root


PAPER = Path(__file__).resolve().parents[1]
OUTPUT = PAPER / "build/generated/pc2-case-macros.tex"
PC2 = "results/granularity/e6/pc2_rolling/"
SOURCES = {
    "native": PC2 + "xeon_20260929_2344/raw/lazy_none/certificate_summary.json",
    "audit": PC2 + "v2/validation/final_artifact_audit.json",
    "projection": PC2 + "v2/validation/endpoint_graphs.json",
}
# Source paths are relative to the artifact root; each pointer names one int.
FIELDS = (
    ("PCTwoCaseCoveredEntries", "native", "/initial_states_in_region"),
    ("PCTwoCaseEntries", "native", "/initial_states"),
    ("PCTwoCaseCertificateStates", "audit", "/certificate_states"),
    ("PCTwoCaseStrategyEdges", "audit", "/strategy_edges"),
    ("PCTwoCaseMaxRank", "audit", "/maximum_rank"),
    ("PCTwoCaseMinOperationalArms", "audit", "/minimum_physical_operational_arms"),
    ("PCTwoCaseLinkedStates", "audit", "/linked_states"),
    ("PCTwoCaseLinkedEdges", "audit", "/linked_edges"),
    ("PCTwoCaseOldProjectedStates", "projection", "/old_endpoint/reachable_product_states"),
    ("PCTwoCaseNewProjectedStates", "projection", "/new_endpoint/reachable_product_states"),
    ("PCTwoCaseOldAdapterStates", "native", "/old_endpoint_states"),
    ("PCTwoCaseNewAdapterStates", "native", "/new_endpoint_states"),
)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def pointer(document, path):
    value = document
    for part in path.lstrip("/").split("/"):
        value = value[part.replace("~1", "/").replace("~0", "~")]
    require(type(value) is int and value >= 0, "Expected a nonnegative integer at " + path)
    return value


def existing_certificate_macro(path):
    matches = re.findall(r"\\newcommand\{\\VThreeESixPCTwoCertificateStates\}\{([0-9]+)\}", path.read_text())
    require(len(matches) == 1, "Expected exactly one existing PC2 certificate-state macro: " + str(path))
    return int(matches[0])


def collect(artifact):
    """Read saved data and return deterministic TeX plus numeric provenance."""
    artifact = Path(artifact).resolve()
    saved = {key: json.loads((artifact / path).read_text()) for key, path in SOURCES.items()}
    native, audit, projection = (saved[key] for key in ("native", "audit", "projection"))
    require(native["decision"] == "WIN", "Saved native fine decision is no longer WIN")
    require(audit["status"] == "PASS" and audit["issues"] == [], "Saved PC2 audit is not PASS")
    require(projection["status"] == "PASS", "Saved endpoint projection is not PASS")
    values = {name: pointer(saved[source], path) for name, source, path in FIELDS}
    require(values["PCTwoCaseCoveredEntries"] == values["PCTwoCaseEntries"] == audit["certificate_initial_states"],
            "Entry coverage differs between preserved native summary and audit")
    require(values["PCTwoCaseOldAdapterStates"] == values["PCTwoCaseEntries"],
            "Old adapter-state and initial-state counts differ")
    require(values["PCTwoCaseCertificateStates"] == native["certificate_states"],
            "Certificate-state counts differ between preserved audit and native summary")
    require(values["PCTwoCaseMaxRank"] == native["worst_completion_rank"],
            "Maximum ranks differ between preserved audit and native summary")
    macro_path = PAPER / "build/generated/base-v3-evidence-macros.tex"
    require(existing_certificate_macro(macro_path) == values["PCTwoCaseCertificateStates"],
            "Existing PC2 certificate macro disagrees with saved audit")
    lines = [
        "% Generated by scripts/generate_pc2_case_macros.py; do not edit numeric values.",
        "% Sources below are relative to the artifact root; suffixes are JSON pointers.",
        "% Projection, adapter, certificate and linked-controller counts use distinct state signatures.",
        "% No bijection between projection and adapter counts is asserted.",
        "% Saved counts only: no new experiment, solver execution or semantic validation.",
    ]
    records = []
    for name, source, path in FIELDS:
        value = values[name]
        lines.extend(["% " + SOURCES[source] + "#" + path,
                      "\\newcommand{\\" + name + "}{" + str(value) + "}"])
        records.append({"macro": name, "source": SOURCES[source], "json_pointer": path, "value": value})
    report = {
        "status": "PASS",
        "macro_count": len(FIELDS),
        "values": values,
        "source_values": records,
        "cross_checks": {
            "covered_entries_equal_entries_and_audit": True,
            "old_adapter_states_equal_entries": True,
            "audit_and_native_certificate_states_equal": True,
            "audit_and_native_maximum_rank_equal": True,
            "local_existing_certificate_macro_matches_saved_audit": True,
        },
        "scope": "Numeric agreement among preserved source JSON and existing macros; no new semantic check or experiment.",
    }
    return "\n".join(lines) + "\n", report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--check", action="store_true", help="Verify source agreement and exact generated bytes without writing")
    modes.add_argument("--emit-patch", action="store_true", help="Emit an apply_patch addition for the missing output")
    parser.add_argument("--artifact-root", type=Path)
    args = parser.parse_args()
    artifact = artifact_root(args.artifact_root)
    output, report = collect(artifact)
    if args.check:
        require(OUTPUT.is_file() and OUTPUT.read_bytes() == output.encode(), "PC2 case macros are missing or stale")
        print(json.dumps({**report, "mode": "check"}, ensure_ascii=False))
        return
    if args.emit_patch:
        require(not OUTPUT.exists(), "--emit-patch only creates the missing output")
        print("*** Begin Patch\n*** Add File: " + str(OUTPUT))
        for line in output.splitlines():
            print("+" + line)
        print("*** End Patch")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)
    print(json.dumps({**report, "mode": "generate"}, ensure_ascii=False))


if __name__ == "__main__":
    main()
