#!/usr/bin/env python3
"""Prepare theorem-linked independent-update LTS inputs inside a campaign.

The generated family is the constructive family used by the paper's
full-expansion separation theorem: K one-state old components, K corresponding
one-state new components, K independent deterministic reconfiguration events,
no requirement handover, and one controllable ``idle`` self-loop.  Generation
is deterministic and refuses to overwrite a different prior preparation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence


SCHEMA_VERSION = "fse2027-independent-lts-family-v1"
GENERATOR_ID = "independent-one-state-reconfiguration-v1"
DEFAULT_SIZES = (2, 4, 6, 8, 10, 12, 16, 20)
BOUNDARY_CASES = (
    "winning",
    "empty_transfer",
    "unsafe_uncontrollable",
    "uncontrollable_livelock",
    "nondeterministic_transfer",
    "unloadable_endpoint",
)


def repository_root() -> Path:
    return Path(__file__).resolve().parents[4]


def inside(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n"
    ).encode("utf-8")


def parse_sizes(value: str) -> List[int]:
    try:
        sizes = [int(token.strip()) for token in value.split(",")]
    except ValueError as error:
        raise argparse.ArgumentTypeError(
            "sizes must be comma-separated integers"
        ) from error
    if not sizes or any(size < 1 or size > 30 for size in sizes):
        raise argparse.ArgumentTypeError("each size must be between 1 and 30")
    if sizes != sorted(set(sizes)):
        raise argparse.ArgumentTypeError(
            "sizes must be unique and strictly increasing"
        )
    return sizes


def joined(names: Iterable[str]) -> str:
    return ", ".join(names)


def render_model(component_count: int) -> str:
    if component_count < 1:
        raise ValueError("component_count must be positive")
    old_components = [
        "OLD_COMPONENT_%d" % index
        for index in range(1, component_count + 1)
    ]
    new_components = [
        "NEW_COMPONENT_%d" % index
        for index in range(1, component_count + 1)
    ]
    relations = [
        "R_COMPONENT_%d_FG" % index
        for index in range(1, component_count + 1)
    ]

    lines = [
        "// Generated by %s; do not edit." % GENERATOR_ID,
        "// K=%d independent one-state component replacements." % component_count,
        "// This is the constructive family for the paper's 2^K Direct-Full",
        "// versus K+1 update-first OTF state separation, not an application model.",
        "",
        "set ControllableActions = {idle}",
        "",
    ]
    lines.extend(
        "%s = (idle -> %s)." % (name, name) for name in old_components
    )
    lines.append("||OldEnvironment = (%s)." % " || ".join(old_components))
    lines.append("")
    lines.extend(
        "%s = (idle -> %s)." % (name, name) for name in new_components
    )
    lines.append("||NewEnvironment = (%s)." % " || ".join(new_components))
    lines.append("")
    for index, (old_name, new_name, relation) in enumerate(
            zip(old_components, new_components, relations), start=1):
        lines.append(
            "relation %s = {%s@%s = reconfigure_COMPONENT_%d -> %s@%s}"
            % (
                relation,
                old_name,
                old_name,
                index,
                new_name,
                new_name,
            )
        )
    lines.extend(
        [
            "",
            "controllerSpec OldSpec = {",
            "    controllable = {ControllableActions}",
            "}",
            "controller ||OldController = OldEnvironment~{OldSpec}.",
            "",
            "controllerSpec NewSpec = {",
            "    controllable = {ControllableActions}",
            "}",
            "controller ||NewController = NewEnvironment~{NewSpec}.",
            "",
            "updatingController IndependentFamily = {",
            "    oldController = OldController,",
            "    newController = NewController,",
            "    oldEnvironment = {%s}," % joined(old_components),
            "    newEnvironment = {%s}," % joined(new_components),
            "    mapRelation = {%s}," % joined(relations),
            "    oldGoal = OldSpec,",
            "    newGoal = NewSpec,",
            "    nonblocking,",
            "    revised_on_the_fly,",
            "    fine_grained",
            "}",
            "||UPDATE_CONTROLLER_OTF_FG = IndependentFamily.",
            "",
        ]
    )
    return "\n".join(lines)


def render_boundary_model(case_id: str) -> tuple[str, str, str]:
    """Return source, expected decision, and the semantic boundary exercised."""
    cases = {
        "winning": {
            "expected": "realizable",
            "boundary": "deterministic safe winning update",
            "controllable": "idle",
            "old": "OLD_COMPONENT = (idle -> OLD_COMPONENT).",
            "new": "NEW_COMPONENT = (idle -> NEW_COMPONENT).",
            "relation": (
                "OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_COMPONENT@NEW_COMPONENT"
            ),
        },
        "empty_transfer": {
            "expected": "unrealizable",
            "boundary": "reachable old endpoint has an empty transfer set",
            "controllable": "idle, enter",
            "old": (
                "OLD_COMPONENT = OLD_READY,\n"
                "OLD_READY = (idle -> OLD_READY | enter -> OLD_ALT),\n"
                "OLD_ALT = (idle -> OLD_ALT)."
            ),
            "new": "NEW_COMPONENT = (idle -> NEW_COMPONENT).",
            "relation": (
                "OLD_ALT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_COMPONENT@NEW_COMPONENT"
            ),
            "transition_property": "ltl_property R_NO_ENTER = [](!enter)",
            "transition": "R_NO_ENTER",
        },
        "unsafe_uncontrollable": {
            "expected": "unrealizable",
            "boundary": "enabled uncontrollable outcome violates update-time safety",
            "controllable": "idle",
            "old": (
                "OLD_COMPONENT = (idle -> OLD_COMPONENT "
                "| fault -> OLD_COMPONENT)."
            ),
            "new": (
                "NEW_COMPONENT = (idle -> NEW_COMPONENT "
                "| fault -> NEW_COMPONENT)."
            ),
            "relation": (
                "OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_COMPONENT@NEW_COMPONENT"
            ),
            "transition_property": (
                "ltl_property R_NO_FAULT = [](!fault)"
            ),
            "transition": "R_NO_FAULT",
        },
        "uncontrollable_livelock": {
            "expected": "unrealizable",
            "boundary": "enabled uncontrollable self-loop prevents strong completion",
            "controllable": "idle",
            "old": (
                "OLD_COMPONENT = (idle -> OLD_COMPONENT "
                "| spin -> OLD_COMPONENT)."
            ),
            "new": (
                "NEW_COMPONENT = (idle -> NEW_COMPONENT "
                "| spin -> NEW_COMPONENT)."
            ),
            "relation": (
                "OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_COMPONENT@NEW_COMPONENT"
            ),
        },
        "nondeterministic_transfer": {
            "expected": "realizable",
            "boundary": "all outcomes of a nondeterministic transfer are winning goals",
            "controllable": "idle, choose, reset",
            "old": "OLD_COMPONENT = (idle -> OLD_COMPONENT).",
            "new": (
                "NEW_COMPONENT = NEW_READY,\n"
                "NEW_READY = (idle -> NEW_READY | choose -> NEW_ALT),\n"
                "NEW_ALT = (idle -> NEW_ALT | reset -> NEW_READY)."
            ),
            "relation": (
                "OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_READY@NEW_COMPONENT,\n"
                "    OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_ALT@NEW_COMPONENT"
            ),
        },
        "unloadable_endpoint": {
            "expected": "unrealizable",
            "boundary": "transferred state has no valid new-requirement activation",
            "controllable": "idle, strand",
            "old": "OLD_COMPONENT = (idle -> OLD_COMPONENT).",
            "new": (
                "NEW_COMPONENT = NEW_READY,\n"
                "NEW_READY = (idle -> NEW_READY | strand -> NEW_STRANDED),\n"
                "NEW_STRANDED = (idle -> NEW_STRANDED)."
            ),
            "relation": (
                "OLD_COMPONENT@OLD_COMPONENT = reconfigure_COMPONENT "
                "-> NEW_STRANDED@NEW_COMPONENT"
            ),
            "new_property": (
                "ltl_property P_NO_STRAND = [](!strand)"
            ),
            "new_safety": "P_NO_STRAND",
        },
    }
    if case_id not in cases:
        raise ValueError("unknown boundary case: " + case_id)
    case = cases[case_id]
    expected = str(case["expected"])
    boundary = str(case["boundary"])
    lines = [
        "// Generated by %s; do not edit." % GENERATOR_ID,
        "// RQ1 semantic boundary: %s." % boundary,
        "// Expected FG-DUCS decision: %s." % expected,
        "",
        "set ControllableActions = {%s}" % case["controllable"],
        "",
        str(case["old"]),
        str(case["new"]),
        "",
        "||OldEnvironment = (OLD_COMPONENT).",
        "||NewEnvironment = (NEW_COMPONENT).",
        "",
        "relation R_COMPONENT_FG = {%s}" % case["relation"],
        "",
    ]
    for property_key in (
            "old_property", "new_property", "transition_property"):
        if property_key in case:
            lines.append(str(case[property_key]))
    if any(
            property_key in case
            for property_key in (
                "old_property", "new_property", "transition_property"
            )):
        lines.append("")
    lines.extend(["controllerSpec OldSpec = {"])
    if "old_safety" in case:
        lines.append("    safety = {%s}" % case["old_safety"])
    lines.extend(["    controllable = {ControllableActions}", "}"])
    if "old_controller" in case:
        lines.append(str(case["old_controller"]))
    else:
        lines.append("controller ||OldController = OldEnvironment~{OldSpec}.")
    lines.extend(["", "controllerSpec NewSpec = {"])
    if "new_safety" in case:
        lines.append("    safety = {%s}" % case["new_safety"])
    lines.extend(
        [
            "    controllable = {ControllableActions}",
            "}",
            "controller ||NewController = NewEnvironment~{NewSpec}.",
            "",
            "updatingController BoundaryCase = {",
            "    oldController = OldController,",
            "    newController = NewController,",
            "    oldEnvironment = {OLD_COMPONENT},",
            "    newEnvironment = {NEW_COMPONENT},",
            "    mapRelation = {R_COMPONENT_FG},",
            "    oldGoal = OldSpec,",
            "    newGoal = NewSpec,",
        ]
    )
    if "transition" in case:
        lines.append("    transition = %s," % case["transition"])
    lines.extend(
        [
            "    nonblocking,",
            "    revised_on_the_fly,",
            "    fine_grained",
            "}",
            "||UPDATE_CONTROLLER_OTF_FG = BoundaryCase.",
            "",
        ]
    )
    return "\n".join(lines), expected, boundary


def atomic_write_exact(path: Path, payload: bytes) -> None:
    if path.exists():
        if not path.is_file() or path.is_symlink():
            raise ValueError("unsafe existing generated path: " + str(path))
        if path.read_bytes() != payload:
            raise ValueError(
                "existing generated file differs; choose a new run id: "
                + str(path)
            )
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=path.name + ".",
        suffix=".tmp",
        dir=str(path.parent),
    )
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except OSError:
            pass
        raise


def prepare(
    campaign: Path,
    base_config_path: Path,
    sizes: Sequence[int],
    root: Path | None = None,
    family_repetitions: int = 5,
    include_boundaries: bool = True,
) -> Dict[str, Any]:
    workspace = repository_root() if root is None else root.resolve()
    sizes = [int(size) for size in sizes]
    if (
        sizes != sorted(set(sizes))
        or any(size < 1 or size > 30 for size in sizes)
    ):
        raise ValueError(
            "sizes must be unique, strictly increasing integers from 1 to 30"
        )
    if family_repetitions < 1 or family_repetitions > 100:
        raise ValueError("family_repetitions must be between 1 and 100")
    campaign = campaign.resolve()
    base_config_path = base_config_path.resolve()
    if not inside(campaign, workspace):
        raise ValueError("campaign must be inside the repository")
    if not base_config_path.is_file() or not inside(base_config_path, workspace):
        raise ValueError("base config must be a repository file")
    base_config_bytes = base_config_path.read_bytes()
    base_config = json.loads(base_config_bytes.decode("utf-8"))
    results_root = (workspace / str(base_config["results_root"])).resolve()
    if campaign.parent != results_root:
        raise ValueError(
            "campaign must be a direct child of configured results_root: "
            + str(results_root)
        )

    input_directory = campaign / "inputs" / "Models"
    expected_names = {
        "independent_k%02d.lts" % component_count
        for component_count in sizes
    }
    if include_boundaries:
        expected_names.update(
            "rq1_%s.lts" % case_id for case_id in BOUNDARY_CASES
        )
    if input_directory.exists():
        extras = sorted(
            path.name
            for path in input_directory.glob("*.lts")
            if path.name not in expected_names
        )
        if extras:
            raise ValueError(
                "generated model directory contains unexpected .lts files: "
                + ", ".join(extras)
            )

    model_payloads: Dict[Path, bytes] = {}
    generated_models: List[Dict[str, Any]] = []
    for component_count in sizes:
        filename = "independent_k%02d.lts" % component_count
        path = input_directory / filename
        payload = render_model(component_count).encode("utf-8")
        model_payloads[path] = payload
        relative = path.relative_to(workspace).as_posix()
        generated_models.append(
            {
                "id": "independent_k%02d" % component_count,
                "path": relative,
                "target_ids": ["base"],
                "repetitions": family_repetitions,
                "family": "independent_one_state_reconfiguration",
                "factors": {
                    "independent_update_events_k": component_count,
                    "requirements": 0,
                    "local_states_per_version": 1,
                    "expected_decision": "realizable",
                    "decision_oracle": (
                        "constructive_initial_update_sequence_then_idle"
                    ),
                    "model_sha256": sha256_bytes(payload),
                },
            }
        )
    boundary_models: List[Dict[str, Any]] = []
    if include_boundaries:
        for case_id in BOUNDARY_CASES:
            filename = "rq1_%s.lts" % case_id
            path = input_directory / filename
            source, expected_decision, boundary = render_boundary_model(case_id)
            payload = source.encode("utf-8")
            model_payloads[path] = payload
            relative = path.relative_to(workspace).as_posix()
            boundary_models.append(
                {
                    "id": "rq1_%s" % case_id,
                    "path": relative,
                    "target_ids": ["base"],
                    "method_ids": ["fg_ducs_otf"],
                    "repetitions": 1,
                    "family": "rq1_semantic_boundary",
                    "factors": {
                        "boundary_case": case_id,
                        "expected_decision": expected_decision,
                        "semantic_boundary": boundary,
                    },
                    "jvm_properties_override": {
                        "mtsa.revised.otf.solver": "otf",
                        "mtsa.otf.guidedStateLimit": "0",
                        "mtsa.otf.guidedQueryLimit": "0",
                        "mtsa.otf.lazyControllableBuckets": "true",
                        "mtsa.otf.controllableActionOrder": "endpoint_guided",
                        "mtsa.revised.otf.independentVerification": "true",
                        "mtsa.revised.otf.independentVerificationMode": "exhaustive",
                        "mtsa.revised.otf.independentStateLimit": "100000",
                        "mtsa.revised.otf.independentQueryLimit": "1000000",
                    },
                }
            )

    runtime_config = json.loads(json.dumps(base_config))
    existing_ids = {str(model["id"]) for model in runtime_config["models"]}
    all_generated_models = generated_models + boundary_models
    collisions = sorted(
        model["id"]
        for model in all_generated_models
        if model["id"] in existing_ids
    )
    if collisions:
        raise ValueError("generated model id collision: " + ", ".join(collisions))
    runtime_config["models"].extend(all_generated_models)
    if sizes and include_boundaries:
        generated_suffix = "-independent-family-and-boundaries"
    elif sizes:
        generated_suffix = "-independent-family"
    elif include_boundaries:
        generated_suffix = "-boundaries"
    else:
        raise ValueError("at least one generated family or boundary is required")
    runtime_config["experiment_id"] = (
        str(base_config["experiment_id"]) + generated_suffix
    )
    runtime_config["description"] = (
        str(base_config.get("description", ""))
        + (
            " Includes the deterministic theorem-linked independent-update "
            "family and six known-decision semantic boundaries."
            if sizes and include_boundaries
            else (
                " Includes the deterministic theorem-linked independent-update "
                "family."
                if sizes
                else " Includes six known-decision semantic boundaries."
            )
        )
    ).strip()
    manifest_path = campaign / "inputs" / "generation_manifest.json"
    runtime_config["generated_input_manifest"] = (
        manifest_path.relative_to(workspace).as_posix()
    )
    protocol_notes = dict(runtime_config.get("protocol_notes", {}))
    protocol_notes.update(
        {
            "evidence_class": (
                "mixed_fixed_descriptive_and_structural_scaling"
                if sizes
                else "formative_fixed_and_semantic_boundary_pilot"
            ),
            "input_scope": (
                "checked_in_lts_plus_campaign_local_generated_concrete_lts"
            ),
            "generated_family": "independent_one_state_reconfiguration",
            "generated_sizes_k": list(sizes),
            "generated_repetitions_per_k": family_repetitions,
            "rq1_boundary_models": (
                list(BOUNDARY_CASES) if include_boundaries else []
            ),
            "rq1_boundary_verification": (
                "independent_exhaustive_fixed_point"
                if include_boundaries
                else "not_in_this_phase"
            ),
            "generated_family_claim_scope": (
                "deterministic structural scaling; not population inference"
            ),
        }
    )
    runtime_config["protocol_notes"] = protocol_notes
    runtime_config_path = campaign / "runtime_config.json"
    runtime_config_payload = canonical_json_bytes(runtime_config)

    manifest_models = []
    independent_items = list(model_payloads.items())[:len(generated_models)]
    for model, (path, payload) in zip(generated_models, independent_items):
        manifest_models.append(
            {
                "id": model["id"],
                "k": model["factors"]["independent_update_events_k"],
                "repetitions": model["repetitions"],
                "path": path.relative_to(campaign).as_posix(),
                "bytes": len(payload),
                "sha256": sha256_bytes(payload),
                "target": "UPDATE_CONTROLLER_OTF_FG",
                "expected_decision": "realizable",
                "decision_oracle": (
                    "constructive_initial_update_sequence_then_idle"
                ),
            }
        )
    manifest_boundaries = []
    boundary_items = list(model_payloads.items())[len(generated_models):]
    for model, (path, payload) in zip(boundary_models, boundary_items):
        manifest_boundaries.append(
            {
                "id": model["id"],
                "case": model["factors"]["boundary_case"],
                "expected_decision": model["factors"]["expected_decision"],
                "path": path.relative_to(campaign).as_posix(),
                "bytes": len(payload),
                "sha256": sha256_bytes(payload),
                "target": "UPDATE_CONTROLLER_OTF_FG",
                "verification_mode": "independent_exhaustive_fixed_point",
            }
        )
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generator_id": GENERATOR_ID,
        "family": "independent_one_state_reconfiguration",
        "sizes_k": list(sizes),
        "construction": {
            "old_local_states_per_component": 1,
            "new_local_states_per_component": 1,
            "reconfiguration_outcomes_per_event": 1,
            "requirements": 0,
            "ordinary_controllable_actions": ["idle"],
            "precedence_constraints": 0,
            "measured_repetitions_per_k": family_repetitions,
            "expected_otf_states_under_update_first_order": "K+1",
            "expected_direct_full_states": "2^K",
            "expected_decision": "realizable",
            "decision_oracle": (
                "At the initial one-state endpoints, execute each controllable "
                "reconfiguration event once, then retain the controllable idle "
                "self-loop."
            ),
        },
        "base_config": {
            "path": base_config_path.relative_to(workspace).as_posix(),
            "bytes": len(base_config_bytes),
            "sha256": sha256_bytes(base_config_bytes),
        },
        "runtime_config": {
            "path": runtime_config_path.relative_to(campaign).as_posix(),
            "bytes": len(runtime_config_payload),
            "sha256": sha256_bytes(runtime_config_payload),
        },
        "models": manifest_models,
        "rq1_boundary_models": manifest_boundaries,
    }
    manifest_payload = canonical_json_bytes(manifest)

    # Validate every existing destination before publishing any missing file.
    expected_payloads = dict(model_payloads)
    expected_payloads[runtime_config_path] = runtime_config_payload
    expected_payloads[manifest_path] = manifest_payload
    for path, payload in expected_payloads.items():
        if path.exists() and (
            not path.is_file()
            or path.is_symlink()
            or path.read_bytes() != payload
        ):
            raise ValueError(
                "existing generated file differs; choose a new run id: "
                + str(path)
            )
    for path, payload in expected_payloads.items():
        atomic_write_exact(path, payload)

    return {
        "status": "READY",
        "campaign": str(campaign),
        "runtime_config": str(runtime_config_path),
        "manifest": str(manifest_path),
        "generated_models": len(generated_models),
        "rq1_boundary_models": len(boundary_models),
        "sizes_k": list(sizes),
        "runtime_config_sha256": sha256_file(runtime_config_path),
    }


def parse_arguments(arguments: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--campaign", type=Path, required=True)
    parser.add_argument("--base-config", type=Path, required=True)
    parser.add_argument(
        "--sizes",
        type=parse_sizes,
        default=None,
        help="strictly increasing comma-separated K values",
    )
    parser.add_argument(
        "--boundary-only",
        action="store_true",
        help="generate only the six RQ1 boundary models (formative pilot)",
    )
    parser.add_argument(
        "--family-only",
        action="store_true",
        help=(
            "generate only the independent-K family; use this for a timing "
            "phase that must not execute the independent boundary checker"
        ),
    )
    parser.add_argument(
        "--family-repetitions",
        type=int,
        default=5,
        help="fresh-JVM repetitions for each K-family model (default: 5)",
    )
    return parser.parse_args(arguments)


def main(arguments: Sequence[str] | None = None) -> int:
    args = parse_arguments(arguments)
    try:
        if args.boundary_only and args.family_only:
            raise ValueError("--boundary-only and --family-only cannot be combined")
        if args.boundary_only and args.sizes is not None:
            raise ValueError("--boundary-only and --sizes cannot be combined")
        sizes = (
            []
            if args.boundary_only
            else (list(DEFAULT_SIZES) if args.sizes is None else args.sizes)
        )
        summary = prepare(
            args.campaign,
            args.base_config,
            sizes,
            family_repetitions=args.family_repetitions,
            include_boundaries=not args.family_only,
        )
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print("GENERATION FAIL: " + str(error), file=sys.stderr)
        return 2
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
