package ltsa.updatingControllers.otf;

import org.json.simple.JSONValue;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Exports the complete reachable strong-reachability game generated by the
 * independent reference semantics.
 *
 * <p>The exporter does not call {@link FineGrainedSuccessorOracle}.  It
 * reconstructs every enabled bucket from the immutable typed problem through
 * {@link IndependentFineGrainedSemantics}, then records enough ownership and
 * outcome information for a solver in another process to reproduce the exact
 * fairness-free decision.  Endpoint preparation remains shared with the MTSA
 * adapter and is therefore an explicit trust boundary of this artifact.</p>
 */
public final class IndependentStrongGameBundleExporter {

    public static final String SCHEMA_VERSION =
            "fse2027-independent-strong-game-bundle-v1";
    public static final String SEMANTICS_ID =
            "java-independent-fg-semantics-complete-reachable-v1";

    private static final String STATE_LIMIT_PROPERTY =
            "mtsa.revised.otf.independentStateLimit";
    private static final String QUERY_LIMIT_PROPERTY =
            "mtsa.revised.otf.independentQueryLimit";

    private IndependentStrongGameBundleExporter() {
    }

    public static void write(
            MtsaRevisedOtfDucsAdapter.Outcome outcome,
            Path destination) throws IOException {
        Objects.requireNonNull(outcome, "outcome");
        long stateLimit = Long.getLong(
                STATE_LIMIT_PROPERTY, Long.valueOf(1_000_000L)).longValue();
        long queryLimit = Long.getLong(
                QUERY_LIMIT_PROPERTY, Long.valueOf(10_000_000L)).longValue();
        Map<String, Object> bundle = export(
                outcome.problem(), outcome.result().isWinning(),
                stateLimit, queryLimit);
        writeNew(destination, bundle);
    }

    static <S, M> Map<String, Object> export(
            FineGrainedUpdateProblem<S, M> problem,
            boolean claimedWinning,
            long stateLimit,
            long queryLimit) {
        Objects.requireNonNull(problem, "problem");
        if (stateLimit < 1L || queryLimit < 1L) {
            throw new IllegalArgumentException(
                    "independent game export limits must be positive");
        }
        UpdatePolicyRestriction.Mode mode =
                UpdatePolicyRestriction.Mode.configured();
        if (mode != UpdatePolicyRestriction.Mode.FULL_FG) {
            throw new IllegalArgumentException(
                    "independent game bundle export currently requires full_fg");
        }
        IndependentFineGrainedSemantics<S, M> semantics =
                new IndependentFineGrainedSemantics<S, M>(problem);
        LinkedHashSet<CanonicalUpdateConfiguration<S, M>> discovered =
                new LinkedHashSet<CanonicalUpdateConfiguration<S, M>>();
        Deque<CanonicalUpdateConfiguration<S, M>> pending =
                new ArrayDeque<CanonicalUpdateConfiguration<S, M>>();
        for (CanonicalUpdateConfiguration<S, M> root
                : sortedStates(semantics.initialStates())) {
            discovered.add(root);
            pending.addLast(root);
        }

        Map<CanonicalUpdateConfiguration<S, M>,
                Map<String, Set<CanonicalUpdateConfiguration<S, M>>>> graph =
                new LinkedHashMap<CanonicalUpdateConfiguration<S, M>,
                        Map<String, Set<CanonicalUpdateConfiguration<S, M>>>>();
        long queries = 0L;
        long outcomes = 0L;
        while (!pending.isEmpty()) {
            CanonicalUpdateConfiguration<S, M> state = pending.removeFirst();
            LinkedHashMap<String, Set<CanonicalUpdateConfiguration<S, M>>>
                    buckets = new LinkedHashMap<String,
                            Set<CanonicalUpdateConfiguration<S, M>>>();
            if (semantics.isSafe(state) && !semantics.isGoal(state)) {
                List<String> actions = new ArrayList<String>(
                        semantics.candidateActions(state));
                Collections.sort(actions);
                for (String action : actions) {
                    queries++;
                    if (queries > queryLimit) {
                        throw new IllegalStateException(
                                "independent game export query limit exceeded");
                    }
                    Set<CanonicalUpdateConfiguration<S, M>> targets =
                            semantics.post(state, action);
                    if (targets.isEmpty()) {
                        continue;
                    }
                    List<CanonicalUpdateConfiguration<S, M>> orderedTargets =
                            sortedStates(targets);
                    LinkedHashSet<CanonicalUpdateConfiguration<S, M>> stable =
                            new LinkedHashSet<CanonicalUpdateConfiguration<S, M>>(
                                    orderedTargets);
                    buckets.put(action, Collections.unmodifiableSet(stable));
                    outcomes += stable.size();
                    for (CanonicalUpdateConfiguration<S, M> target : stable) {
                        if (discovered.add(target)) {
                            if (discovered.size() > stateLimit) {
                                throw new IllegalStateException(
                                        "independent game export state limit exceeded");
                            }
                            pending.addLast(target);
                        }
                    }
                }
            }
            graph.put(state, Collections.unmodifiableMap(buckets));
        }

        List<CanonicalUpdateConfiguration<S, M>> states =
                sortedStates(discovered);
        LinkedHashMap<CanonicalUpdateConfiguration<S, M>, String> identifiers =
                new LinkedHashMap<CanonicalUpdateConfiguration<S, M>, String>();
        for (int index = 0; index < states.size(); index++) {
            identifiers.put(states.get(index), "Q" + index);
        }

        List<Object> stateRecords = new ArrayList<Object>();
        List<String> initialIds = new ArrayList<String>();
        List<String> goalIds = new ArrayList<String>();
        for (CanonicalUpdateConfiguration<S, M> state : states) {
            String id = identifiers.get(state);
            boolean initial = semantics.initialStates().contains(state);
            boolean safe = semantics.isSafe(state);
            boolean goal = semantics.isGoal(state);
            if (initial) initialIds.add(id);
            if (goal) goalIds.add(id);
            LinkedHashMap<String, Object> record =
                    new LinkedHashMap<String, Object>();
            record.put("id", id);
            record.put("initial", Boolean.valueOf(initial));
            record.put("safe", Boolean.valueOf(safe));
            record.put("goal", Boolean.valueOf(goal));
            record.put("physical", state.physicalState().toString());
            record.put("active_testers", sortedMap(
                    state.testerStatesByRequirementId()));
            record.put("pending_actions", sortedStrings(
                    state.pendingActions()));
            stateRecords.add(record);
        }

        List<Object> bucketRecords = new ArrayList<Object>();
        long controllableBuckets = 0L;
        long uncontrollableBuckets = 0L;
        for (CanonicalUpdateConfiguration<S, M> state : states) {
            Map<String, Set<CanonicalUpdateConfiguration<S, M>>> buckets =
                    graph.get(state);
            if (buckets == null) continue;
            for (Map.Entry<String, Set<CanonicalUpdateConfiguration<S, M>>>
                    entry : buckets.entrySet()) {
                boolean controllable = semantics.isControllable(entry.getKey());
                if (controllable) controllableBuckets++;
                else uncontrollableBuckets++;
                LinkedHashMap<String, Object> record =
                        new LinkedHashMap<String, Object>();
                record.put("source", identifiers.get(state));
                record.put("action", entry.getKey());
                record.put("controllable", Boolean.valueOf(controllable));
                List<String> targetIds = new ArrayList<String>();
                for (CanonicalUpdateConfiguration<S, M> target
                        : entry.getValue()) {
                    targetIds.add(identifiers.get(target));
                }
                record.put("targets", targetIds);
                bucketRecords.add(record);
            }
        }

        LinkedHashMap<String, Object> root = new LinkedHashMap<String, Object>();
        root.put("schema_version", SCHEMA_VERSION);
        root.put("semantics_id", SEMANTICS_ID);
        root.put("policy_restriction", mode.propertyValue());
        root.put("claimed_decision",
                claimedWinning ? "realizable" : "unrealizable");
        root.put("state_count", Long.valueOf(states.size()));
        root.put("query_count", Long.valueOf(queries));
        root.put("outcome_edge_count", Long.valueOf(outcomes));
        root.put("controllable_bucket_count",
                Long.valueOf(controllableBuckets));
        root.put("uncontrollable_bucket_count",
                Long.valueOf(uncontrollableBuckets));
        root.put("initial_state_ids", initialIds);
        root.put("goal_state_ids", goalIds);
        root.put("states", stateRecords);
        root.put("buckets", bucketRecords);
        return Collections.unmodifiableMap(root);
    }

    private static void writeNew(
            Path destination,
            Map<String, Object> bundle) throws IOException {
        Objects.requireNonNull(destination, "destination");
        Path absolute = destination.toAbsolutePath().normalize();
        Path parent = absolute.getParent();
        if (parent != null) Files.createDirectories(parent);
        if (Files.exists(absolute)) {
            throw new IOException(
                    "Refusing to overwrite independent game bundle: " + absolute);
        }
        try (BufferedWriter writer = Files.newBufferedWriter(
                absolute,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE_NEW,
                StandardOpenOption.WRITE)) {
            JSONValue.writeJSONString(bundle, writer);
            writer.newLine();
        }
    }

    private static <S, M> List<CanonicalUpdateConfiguration<S, M>> sortedStates(
            java.util.Collection<CanonicalUpdateConfiguration<S, M>> values) {
        List<CanonicalUpdateConfiguration<S, M>> result =
                new ArrayList<CanonicalUpdateConfiguration<S, M>>(values);
        Collections.sort(result,
                Comparator.comparing(CanonicalUpdateConfiguration::toString));
        return result;
    }

    private static List<String> sortedStrings(
            java.util.Collection<String> values) {
        List<String> result = new ArrayList<String>(values);
        Collections.sort(result);
        return result;
    }

    private static <M> Map<String, Object> sortedMap(Map<String, M> values) {
        List<String> keys = new ArrayList<String>(values.keySet());
        Collections.sort(keys);
        LinkedHashMap<String, Object> result =
                new LinkedHashMap<String, Object>();
        for (String key : keys) {
            result.put(key, String.valueOf(values.get(key)));
        }
        return result;
    }
}
